const books = [
	// Հիմնականը
	{
		category: "Հիմնականը",
		title: "Երգարան",
		slug: "Song",
		cover: "/books/Song/cover.jpg",
		chapters: [
			"/books/Song/01.md",
			"/books/Song/02.md",
			"/books/Song/03.md",
			"/books/Song/04.md",
			"/books/Song/05.md",
			"/books/Song/06.md",
			"/books/Song/07.md",
			"/books/Song/08.md",
			"/books/Song/09.md",
			"/books/Song/10.md",
			"/books/Song/11.md",
			"/books/Song/12.md",
			"/books/Song/13.md",
			"/books/Song/14.md",
			"/books/Song/15.md",
			"/books/Song/16.md",
			"/books/Song/17.md",
			"/books/Song/18.md",
			"/books/Song/19.md",
			"/books/Song/20.md",
		],
	},
	{
		category: "Հիմնականը",
		title: "Մարկոսի ավետարան",
		slug: "GospelofMark",
		cover: "/books/GospelofMark/cover.jpg",
		chapters: ["/books/GospelofMark/01.md", "/books/GospelofMark/02.md"],
	},
	{
		category: "Հիմնականը",
		title: "Ղուկասի Ավետարան",
		slug: "GospelofLuke",
		cover: "/books/GospelofLuke/cover.jpg",
		chapters: ["/books/GospelofLuke/01.md", "/books/GospelofLuke/02.md"],
	},
	{
		category: "Հիմնականը",
		title: "Յովհաննու Ավետարան",
		slug: "GospelofJohn",
		cover: "/books/GospelofJohn/cover.jpg",
		chapters: ["/books/GospelofJohn/01.md", "/books/GospelofJohn/02.md"],
	},
	{
		category: "tutorials",
		title: "PHP book title",
		slug: "phpBook01",
		cover: "/books/php/cover.jpg",
		chapters: ["/books/php/01.md", "/books/php/02.md", "/books/php/03.md"],
	},
	{
		category: "tutorials",
		title: "JS book title",
		slug: "jsBook01",
		cover: "/books/js/cover.jpg",
		chapters: ["/books/js/01.md", "/books/js/02.md"],
	},
	{
		category: "tutorials",
		title: "HTML book title",
		slug: "htmlBook01",
		cover: "/books/html/cover.jpg",
		chapters: [
			"/books/html/01.md",
			"/books/html/02.md",
			"/books/html/02.md",
		],
	},
	{
		category: "tasks",
		title: "PHP task book title",
		slug: "phpTasks01",
		cover: "/books/php/cover.jpg",
		chapters: ["/books/php/01.md", "/books/php/02.md", "/books/php/03.md"],
	},
	{
		category: "tasks",
		title: "JS task book title",
		slug: "jsTasks01",
		cover: "/books/js/cover.jpg",
		chapters: ["/books/js/01.md", "/books/js/02.md"],
	},
	{
		category: "tasks",
		title: "HTML task book title",
		slug: "htmlTasks01",
		cover: "/books/html/cover.jpg",
		chapters: [
			"/books/html/01.md",
			"/books/html/02.md",
			"/books/html/02.md",
		],
	},
	{
		category: "taskBook",
		title: "JS task book title",
		slug: "jsTasks01",
		cover: "/books/js/cover.jpg",
		chapters: ["/books/js/01.md", "/books/js/02.md"],
	},
];

export default books;
