const books = [
	// ++++++++++++++++++++++++++++++++++++++++++++Հիմնականը
	{
		category: "Հիմնականը",
		title: "Երգարան",
		slug: "Song",
		cover: "/books/Song/cover.jpg",
		chapters: [
			"/books/Song/01.md",
			"/books/Song/02.md",
			"/books/Song/03.md",
			"/books/Song/04.md",
			"/books/Song/05.md",
			"/books/Song/06.md",
			"/books/Song/07.md",
			"/books/Song/08.md",
			"/books/Song/09.md",
			"/books/Song/10.md",
			"/books/Song/11.md",
			"/books/Song/12.md",
			"/books/Song/13.md",
			"/books/Song/14.md",
			"/books/Song/15.md",
			"/books/Song/16.md",
			"/books/Song/17.md",
			"/books/Song/18.md",
			"/books/Song/19.md",
			"/books/Song/20.md",
		],
	},
	{
		category: "Հիմնականը",
		title: "Մեսրոպ Մաշտոց",
		slug: "MesropMashtoc",
		cover: "/books/MesropMashtoc/cover.jpg",
		chapters: ["/books/MesropMashtoc/01.md", "/books/MesropMashtoc/02.md"],
	},
	{
		category: "Հիմնականը",
		title: "Սաղմոսներ",
		slug: "Psalm",
		cover: "/books/Psalm/cover.jpg",
		chapters: ["/books/Psalm/01.md", "/books/Psalm/02.md"],
	},

	// +++++++++++++++++++++++++++++НОВЫЙ ЗАВЕТ ++++++++++++++++++++++++++++++++++
	{
		category: "tutorials",
		title: "Մատթեոսի Ավետարան",
		slug: "GospelMat",
		cover: "/books/GospelMat/cover.jpg",
		chapters: [
			"/books/GospelMat/01.md",
			"/books/GospelMat/02.md",
			"/books/GospelMat/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Մարկոսի Ավետարան",
		slug: "GospelMark",
		cover: "/books/GospelMark/cover.jpg",
		chapters: ["/books/GospelMark/01.md", "/books/GospelMark/02.md"],
	},
	{
		category: "tutorials",
		title: "Ղուկասի Ավետարան",
		slug: "GospelLuke",
		cover: "/books/GospelLuke/cover.jpg",
		chapters: [
			"/books/GospelLuke/01.md",
			"/books/GospelLuke/02.md",
			"/books/GospelLuke/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Յովհաննու Ավետարան",
		slug: "GospelJohn",
		cover: "/books/GospelJohn/cover.jpg",
		chapters: [
			"/books/GospelJohn/01.md",
			"/books/GospelJohn/02.md",
			"/books/GospelJohn/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Գործք Առաքելոց",
		slug: "Acts",
		cover: "/books/Acts/cover.jpg",
		chapters: [
			"/books/Acts/01.md",
			"/books/Acts/02.md",
			"/books/Acts/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Rome",
		slug: "Rome",
		cover: "/books/Rome/cover.jpg",
		chapters: [
			"/books/Rome/01.md",
			"/books/Rome/02.md",
			"/books/Rome/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Korinf1",
		slug: "Korinf1",
		cover: "/books/Korinf1/cover.jpg",
		chapters: [
			"/books/Korinf1/01.md",
			"/books/Korinf1/02.md",
			"/books/Korinf1/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Korinf2",
		slug: "Korinf2",
		cover: "/books/Korinf2/cover.jpg",
		chapters: [
			"/books/Korinf2/01.md",
			"/books/Korinf2/02.md",
			"/books/Korinf2/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Galat",
		slug: "Galat",
		cover: "/books/Galat/cover.jpg",
		chapters: [
			"/books/Galat/01.md",
			"/books/Galat/02.md",
			"/books/Galat/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Epesaciner",
		slug: "Epesaciner",
		cover: "/books/Epesaciner/cover.jpg",
		chapters: [
			"/books/Epesaciner/01.md",
			"/books/Epesaciner/02.md",
			"/books/Epesaciner/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Filipic",
		slug: "Filipic",
		cover: "/books/Filipic/cover.jpg",
		chapters: [
			"/books/Filipic/01.md",
			"/books/Filipic/02.md",
			"/books/Filipic/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Kolosaciner",
		slug: "Kolosaciner",
		cover: "/books/Kolosaciner/cover.jpg",
		chapters: [
			"/books/Kolosaciner/01.md",
			"/books/Kolosaciner/02.md",
			"/books/Kolosaciner/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Tesagonikaciner1",
		slug: "Tesagonikaciner1",
		cover: "/books/Tesagonikaciner1/cover.jpg",
		chapters: [
			"/books/Tesagonikaciner1/01.md",
			"/books/Tesagonikaciner1/02.md",
			"/books/Tesagonikaciner1/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Tesagonikaciner2",
		slug: "Tesagonikaciner2",
		cover: "/books/Tesagonikaciner2/cover.jpg",
		chapters: [
			"/books/Tesagonikaciner2/01.md",
			"/books/Tesagonikaciner2/02.md",
			"/books/Tesagonikaciner2/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Timofey1",
		slug: "Timofey1",
		cover: "/books/Timofey1/cover.jpg",
		chapters: [
			"/books/Timofey1/01.md",
			"/books/Timofey1/02.md",
			"/books/Timofey1/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Timofey2",
		slug: "Timofey2",
		cover: "/books/Timofey2/cover.jpg",
		chapters: [
			"/books/Timofey2/01.md",
			"/books/Timofey2/02.md",
			"/books/Timofey2/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Titos",
		slug: "Titos",
		cover: "/books/Titos/cover.jpg",
		chapters: [
			"/books/Titos/01.md",
			"/books/Titos/02.md",
			"/books/Titos/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Filimon",
		slug: "Filimon",
		cover: "/books/Filimon/cover.jpg",
		chapters: [
			"/books/Filimon/01.md",
			"/books/Filimon/02.md",
			"/books/Filimon/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Evreyam",
		slug: "Evreyam",
		cover: "/books/Evreyam/cover.jpg",
		chapters: [
			"/books/Evreyam/01.md",
			"/books/Evreyam/02.md",
			"/books/Evreyam/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Yakov",
		slug: "Yakov",
		cover: "/books/Yakov/cover.jpg",
		chapters: [
			"/books/Yakov/01.md",
			"/books/Yakov/02.md",
			"/books/Yakov/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Petros1",
		slug: "Petros1",
		cover: "/books/Petros1/cover.jpg",
		chapters: [
			"/books/Petros1/01.md",
			"/books/Petros1/02.md",
			"/books/Petros1/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Petros2",
		slug: "Petros2",
		cover: "/books/Petros2/cover.jpg",
		chapters: [
			"/books/Petros2/01.md",
			"/books/Petros2/02.md",
			"/books/Petros2/03.md",
		],
	},
	{
		category: "tutorials",
		title: "John1",
		slug: "John1",
		cover: "/books/John1/cover.jpg",
		chapters: [
			"/books/John1/01.md",
			"/books/John1/02.md",
			"/books/John1/03.md",
		],
	},
	{
		category: "tutorials",
		title: "John2",
		slug: "John2",
		cover: "/books/John2/cover.jpg",
		chapters: [
			"/books/John2/01.md",
			"/books/John2/02.md",
			"/books/John2/03.md",
		],
	},
	{
		category: "tutorials",
		title: "John3",
		slug: "John3",
		cover: "/books/John3/cover.jpg",
		chapters: [
			"/books/John3/01.md",
			"/books/John3/02.md",
			"/books/John3/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Yuda",
		slug: "Yuda",
		cover: "/books/Yuda/cover.jpg",
		chapters: [
			"/books/Yuda/01.md",
			"/books/Yuda/02.md",
			"/books/Yuda/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Haytnutyun",
		slug: "Haytnutyun",
		cover: "/books/Haytnutyun/cover.jpg",
		chapters: [
			"/books/Haytnutyun/01.md",
			"/books/Haytnutyun/02.md",
			"/books/Haytnutyun/03.md",
		],
	},

	// +++++++++++++++++++++++++++ОТЦЫ ВЕРЫ++++++++++++++++++++++++++++++++++++++++++++
	{
		category: "tasks",
		title: "Lusavorich",
		slug: "Lusavorich",
		cover: "/books/Lusavorich/cover.jpg",
		chapters: ["/books/Lusavorich/01.md", "/books/Lusavorich/02.md"],
	},
	{
		category: "tasks",
		title: "Tumanyan",
		slug: "Tumanyan",
		cover: "/books/Tumanyan/cover.jpg",
		chapters: ["/books/Tumanyan/01.md", "/books/Tumanyan/02.md"],
	},
	{
		category: "tasks",
		title: "Narekaci",
		slug: "Narekaci",
		cover: "/books/Narekaci/cover.jpg",
		chapters: [
			"/books/Narekaci/01.md",
			"/books/Narekaci/02.md",
			"/books/Narekaci/02.md",
		],
	},
	{
		category: "tasks",
		title: "Nerses",
		slug: "Nerses",
		cover: "/books/Nerses/cover.jpg",
		chapters: [
			"/books/Nerses/01.md",
			"/books/Nerses/02.md",
			"/books/Nerses/02.md",
		],
	},
	{
		category: "tasks",
		title: "Xorenaci",
		slug: "Xorenaci",
		cover: "/books/Xorenaci/cover.jpg",
		chapters: [
			"/books/Xorenaci/01.md",
			"/books/Xorenaci/02.md",
			"/books/Xorenaci/02.md",
		],
	},

	// +++++++++++++++++++++++++++++++++++++ВЕТХИЙ ЗАВЕТ+++++++++++++++++++++++++++++++++
	{
		category: "taskBook",
		title: "Esaya",
		slug: "Esaya",
		cover: "/books/Esaya/cover.jpg",
		chapters: ["/books/Esaya/01.md", "/books/Esaya/02.md"],
	},
	{
		category: "taskBook",
		title: "Daniel",
		slug: "Daniel",
		cover: "/books/Daniel/cover.jpg",
		chapters: ["/books/Daniel/01.md", "/books/Daniel/02.md"],
	},
	{
		category: "taskBook",
		title: "Sofonia",
		slug: "Sofonia",
		cover: "/books/Sofonia/cover.jpg",
		chapters: ["/books/Sofonia/01.md", "/books/Sofonia/02.md"],
	},
];

export default books;
