const books = [
	// ++++++++++++++++++++++++++++++++++++++++++++Հիմնականը
	{
		category: "Հիմնականը",
		title: "Երգարան",
		slug: "Song",
		cover: "/books/Song/cover.jpg",
		chapters: [
			"/books/Song/01.md",
			"/books/Song/02.md",
			"/books/Song/03.md",
			"/books/Song/04.md",
			"/books/Song/05.md",
			"/books/Song/06.md",
			"/books/Song/07.md",
			"/books/Song/08.md",
			"/books/Song/09.md",
			"/books/Song/10.md",
			"/books/Song/11.md",
			"/books/Song/12.md",
			"/books/Song/13.md",
			"/books/Song/14.md",
			"/books/Song/15.md",
			"/books/Song/16.md",
			"/books/Song/17.md",
			"/books/Song/18.md",
			"/books/Song/19.md",
			"/books/Song/20.md",
			"/books/Song/21.md",
			"/books/Song/22.md",
			"/books/Song/23.md",
			"/books/Song/24.md",
			"/books/Song/25.md",
			"/books/Song/26.md",
			"/books/Song/27.md",
			"/books/Song/28.md",
			"/books/Song/29.md",
			"/books/Song/30.md",
			"/books/Song/31.md",
			"/books/Song/32.md",
			"/books/Song/33.md",
			"/books/Song/34.md",
			"/books/Song/35.md",
			"/books/Song/36.md",
			"/books/Song/37.md",
			"/books/Song/38.md",
			"/books/Song/39.md",
			"/books/Song/40.md",
			"/books/Song/41.md",
			"/books/Song/42.md",
			"/books/Song/43.md",
			"/books/Song/44.md",
			"/books/Song/45.md",
			"/books/Song/46.md",
			"/books/Song/47.md",
			"/books/Song/48.md",
			"/books/Song/49.md",
			"/books/Song/50.md",
			"/books/Song/51.md",
			"/books/Song/52.md",
			"/books/Song/53.md",
			"/books/Song/54.md",
			"/books/Song/55.md",
			"/books/Song/56.md",
			"/books/Song/57.md",
			"/books/Song/58.md",
			"/books/Song/59.md",
			"/books/Song/60.md",
			"/books/Song/61.md",
			"/books/Song/62.md",
			"/books/Song/63.md",
			"/books/Song/64.md",
			"/books/Song/65.md",
			"/books/Song/66.md",
			"/books/Song/67.md",
			"/books/Song/68.md",
			"/books/Song/69.md",
			"/books/Song/70.md",
			"/books/Song/71.md",
			"/books/Song/72.md",
			"/books/Song/73.md",
			"/books/Song/74.md",
			"/books/Song/75.md",
			"/books/Song/76.md",
			"/books/Song/77.md",
			"/books/Song/78.md",
			"/books/Song/79.md",
			"/books/Song/80.md",
			"/books/Song/81.md",
			"/books/Song/82.md",
			"/books/Song/83.md",
			"/books/Song/84.md",
			"/books/Song/85.md",
			"/books/Song/86.md",
			"/books/Song/87.md",
			"/books/Song/88.md",
			"/books/Song/89.md",
			"/books/Song/90.md",
			"/books/Song/91.md",
			"/books/Song/92.md",
			"/books/Song/93.md",
			"/books/Song/94.md",
			"/books/Song/95.md",
			"/books/Song/96.md",
			"/books/Song/97.md",
			"/books/Song/98.md",
			"/books/Song/99.md",
			"/books/Song/100.md",
			"/books/Song/101.md",
			"/books/Song/102.md",
			"/books/Song/103.md",
			"/books/Song/104.md",
			"/books/Song/105.md",
			"/books/Song/106.md",
			"/books/Song/107.md",
			"/books/Song/108.md",
			"/books/Song/109.md",
			"/books/Song/110.md",
			"/books/Song/111.md",
			"/books/Song/112.md",
			"/books/Song/113.md",
			"/books/Song/114.md",
			"/books/Song/115.md",
			"/books/Song/116.md",
			"/books/Song/117.md",
			"/books/Song/118.md",
			"/books/Song/119.md",
			"/books/Song/120.md",
			"/books/Song/121.md",
			"/books/Song/122.md",
			"/books/Song/123.md",
			"/books/Song/124.md",
			"/books/Song/125.md",
			"/books/Song/126.md",
			"/books/Song/127.md",
			"/books/Song/128.md",
			"/books/Song/129.md",
			"/books/Song/130.md",
			"/books/Song/131.md",
			"/books/Song/132.md",
			"/books/Song/133.md",
			"/books/Song/134.md",
			"/books/Song/135.md",
			"/books/Song/136.md",
			"/books/Song/137.md",
			"/books/Song/138.md",
			"/books/Song/139.md",
			"/books/Song/140.md",
			"/books/Song/141.md",
			"/books/Song/142.md",
			"/books/Song/143.md",
			"/books/Song/144.md",
			"/books/Song/145.md",
			"/books/Song/146.md",
			"/books/Song/147.md",
			"/books/Song/148.md",
			"/books/Song/149.md",
			"/books/Song/150.md",
			"/books/Song/151.md",
			"/books/Song/152.md",
			"/books/Song/153.md",
			"/books/Song/154.md",
			"/books/Song/155.md",
			"/books/Song/156.md",
			"/books/Song/157.md",
			"/books/Song/158.md",
			"/books/Song/159.md",
			"/books/Song/160.md",
			"/books/Song/161.md",
			"/books/Song/162.md",
			"/books/Song/163.md",
			"/books/Song/164.md",
			"/books/Song/165.md",
			"/books/Song/166.md",
			"/books/Song/167.md",
			"/books/Song/168.md",
			"/books/Song/169.md",
			"/books/Song/170.md",
			"/books/Song/171.md",
			"/books/Song/172.md",
			"/books/Song/173.md",
			"/books/Song/174.md",
			"/books/Song/175.md",
			"/books/Song/176.md",
			"/books/Song/177.md",
			"/books/Song/178.md",
			"/books/Song/179.md",
			"/books/Song/180.md",
			"/books/Song/181.md",
			"/books/Song/182.md",
			"/books/Song/183.md",
			"/books/Song/184.md",
			"/books/Song/185.md",
			"/books/Song/186.md",
			"/books/Song/187.md",
			"/books/Song/188.md",
			"/books/Song/189.md",
			"/books/Song/190.md",
			"/books/Song/191.md",
			"/books/Song/192.md",
			"/books/Song/193.md",
			"/books/Song/194.md",
			"/books/Song/195.md",
			"/books/Song/196.md",
			"/books/Song/197.md",
			"/books/Song/198.md",
			"/books/Song/199.md",
			"/books/Song/200.md",
			"/books/Song/201.md",
			"/books/Song/202.md",
			"/books/Song/203.md",
			"/books/Song/204.md",
			"/books/Song/205.md",
			"/books/Song/206.md",
			"/books/Song/207.md",
			"/books/Song/208.md",
			"/books/Song/209.md",
			"/books/Song/210.md",
			"/books/Song/211.md",
			"/books/Song/212.md",
			"/books/Song/213.md",
			"/books/Song/214.md",
			"/books/Song/215.md",
			"/books/Song/216.md",
			"/books/Song/217.md",
			"/books/Song/218.md",
			"/books/Song/219.md",
			"/books/Song/220.md",
			"/books/Song/221.md",
			"/books/Song/222.md",
			"/books/Song/223.md",
			"/books/Song/224.md",
			"/books/Song/225.md",
			"/books/Song/226.md",
			"/books/Song/227.md",
			"/books/Song/228.md",
			"/books/Song/229.md",
			"/books/Song/230.md",
			"/books/Song/231.md",
			"/books/Song/232.md",
			"/books/Song/233.md",
			"/books/Song/234.md",
			"/books/Song/235.md",
			"/books/Song/236.md",
			"/books/Song/237.md",
			"/books/Song/238.md",
			"/books/Song/239.md",
			"/books/Song/240.md",
			"/books/Song/241.md",
			"/books/Song/242.md",
			"/books/Song/243.md",
			"/books/Song/244.md",
			"/books/Song/245.md",
			"/books/Song/246.md",
			"/books/Song/247.md",
			"/books/Song/248.md",
			"/books/Song/249.md",
			"/books/Song/250.md",
			"/books/Song/251.md",
			"/books/Song/252.md",
			"/books/Song/253.md",
			"/books/Song/254.md",
			"/books/Song/255.md",
			"/books/Song/256.md",
			"/books/Song/257.md",
			"/books/Song/258.md",
			"/books/Song/259.md",
			"/books/Song/260.md",
			"/books/Song/261.md",
			"/books/Song/262.md",
			"/books/Song/263.md",
			"/books/Song/264.md",
			"/books/Song/265.md",
			"/books/Song/266.md",
			"/books/Song/267.md",
			"/books/Song/268.md",
			"/books/Song/269.md",
			"/books/Song/270.md",
			"/books/Song/271.md",
			"/books/Song/272.md",
			"/books/Song/273.md",
			"/books/Song/274.md",
			"/books/Song/275.md",
			"/books/Song/276.md",
			"/books/Song/277.md",
			"/books/Song/278.md",
			"/books/Song/279.md",
			"/books/Song/280.md",
			"/books/Song/281.md",
			"/books/Song/282.md",
			"/books/Song/283.md",
			"/books/Song/284.md",
			"/books/Song/285.md",
			"/books/Song/286.md",
			"/books/Song/287.md",
			"/books/Song/288.md",
			"/books/Song/289.md",
			"/books/Song/290.md",
			"/books/Song/291.md",
			"/books/Song/292.md",
			"/books/Song/293.md",
			"/books/Song/294.md",
			"/books/Song/295.md",
			"/books/Song/296.md",
			"/books/Song/297.md",
			"/books/Song/298.md",
			"/books/Song/299.md",
			"/books/Song/300.md",
			"/books/Song/301.md",
			"/books/Song/302.md",
			"/books/Song/303.md",
			"/books/Song/304.md",
			"/books/Song/305.md",
			"/books/Song/306.md",
			"/books/Song/307.md",
			"/books/Song/308.md",
			"/books/Song/309.md",
			"/books/Song/310.md",
			"/books/Song/311.md",
			"/books/Song/312.md",
			"/books/Song/313.md",
			"/books/Song/314.md",
			"/books/Song/315.md",
			"/books/Song/316.md",
			"/books/Song/317.md",
			"/books/Song/318.md",
			"/books/Song/319.md",
			"/books/Song/320.md",
			"/books/Song/321.md",
			"/books/Song/322.md",
			"/books/Song/323.md",
			"/books/Song/324.md",
			"/books/Song/325.md",
			"/books/Song/326.md",
			"/books/Song/327.md",
			"/books/Song/328.md",
			"/books/Song/329.md",
			"/books/Song/330.md",
			"/books/Song/331.md",
			"/books/Song/332.md",
			"/books/Song/333.md",
			"/books/Song/334.md",
			"/books/Song/335.md",
			"/books/Song/336.md",
			"/books/Song/337.md",
			"/books/Song/338.md",
			"/books/Song/339.md",
			"/books/Song/340.md",
			"/books/Song/341.md",
			"/books/Song/342.md",
			"/books/Song/343.md",
			"/books/Song/344.md",
			"/books/Song/345.md",
			"/books/Song/346.md",
			"/books/Song/347.md",
			"/books/Song/348.md",
			"/books/Song/349.md",
			"/books/Song/350.md",
			"/books/Song/351.md",
			"/books/Song/352.md",
			"/books/Song/353.md",
			"/books/Song/354.md",
			"/books/Song/355.md",
			"/books/Song/356.md",
			"/books/Song/357.md",
			"/books/Song/358.md",
			"/books/Song/359.md",
			"/books/Song/360.md",
			"/books/Song/361.md",
			"/books/Song/362.md",
			"/books/Song/363.md",
			"/books/Song/364.md",
			"/books/Song/365.md",
			"/books/Song/366.md",
			"/books/Song/367.md",
			"/books/Song/368.md",
			"/books/Song/369.md",
			"/books/Song/370.md",
			"/books/Song/371.md",
			"/books/Song/372.md",
			"/books/Song/373.md",
			"/books/Song/374.md",
			"/books/Song/375.md",
			"/books/Song/376.md",
			"/books/Song/377.md",
			"/books/Song/378.md",
			"/books/Song/379.md",
			"/books/Song/380.md",
			"/books/Song/381.md",
			"/books/Song/382.md",
			"/books/Song/383.md",
			"/books/Song/384.md",
			"/books/Song/385.md",
			"/books/Song/386.md",
			"/books/Song/387.md",
			"/books/Song/388.md",
			"/books/Song/389.md",
			"/books/Song/390.md",
			"/books/Song/391.md",
			"/books/Song/392.md",
			"/books/Song/393.md",
			"/books/Song/394.md",
			"/books/Song/395.md",
			"/books/Song/396.md",
			"/books/Song/397.md",
			"/books/Song/398.md",
			"/books/Song/399.md",
			"/books/Song/400.md",
		],
	},
	{
		category: "Հիմնականը",
		title: "Մեսրոպ Մաշտոց",
		slug: "MesropMashtoc",
		cover: "/books/MesropMashtoc/cover.jpg",
		chapters: ["/books/MesropMashtoc/01.md", "/books/MesropMashtoc/02.md"],
	},
	{
		category: "Հիմնականը",
		title: "Սաղմոսներ",
		slug: "Psalm",
		cover: "/books/Psalm/cover.jpg",
		chapters: ["/books/Psalm/01.md", "/books/Psalm/02.md"],
	},

	// +++++++++++++++++++++++++++++НОВЫЙ ЗАВЕТ ++++++++++++++++++++++++++++++++++
	{
		category: "tutorials",
		title: "Մատթեոսի Ավետարան",
		slug: "GospelMat",
		cover: "/books/GospelMat/cover.jpg",
		chapters: [
			"/books/GospelMat/01.md",
			"/books/GospelMat/02.md",
			"/books/GospelMat/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Մարկոսի Ավետարան",
		slug: "GospelMark",
		cover: "/books/GospelMark/cover.jpg",
		chapters: ["/books/GospelMark/01.md", "/books/GospelMark/02.md"],
	},
	{
		category: "tutorials",
		title: "Ղուկասի Ավետարան",
		slug: "GospelLuke",
		cover: "/books/GospelLuke/cover.jpg",
		chapters: [
			"/books/GospelLuke/01.md",
			"/books/GospelLuke/02.md",
			"/books/GospelLuke/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Յովհաննու Ավետարան",
		slug: "GospelJohn",
		cover: "/books/GospelJohn/cover.jpg",
		chapters: [
			"/books/GospelJohn/01.md",
			"/books/GospelJohn/02.md",
			"/books/GospelJohn/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Գործք Առաքելոց",
		slug: "Acts",
		cover: "/books/Acts/cover.jpg",
		chapters: [
			"/books/Acts/01.md",
			"/books/Acts/02.md",
			"/books/Acts/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Rome",
		slug: "Rome",
		cover: "/books/Rome/cover.jpg",
		chapters: [
			"/books/Rome/01.md",
			"/books/Rome/02.md",
			"/books/Rome/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Korinf1",
		slug: "Korinf1",
		cover: "/books/Korinf1/cover.jpg",
		chapters: [
			"/books/Korinf1/01.md",
			"/books/Korinf1/02.md",
			"/books/Korinf1/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Korinf2",
		slug: "Korinf2",
		cover: "/books/Korinf2/cover.jpg",
		chapters: [
			"/books/Korinf2/01.md",
			"/books/Korinf2/02.md",
			"/books/Korinf2/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Galat",
		slug: "Galat",
		cover: "/books/Galat/cover.jpg",
		chapters: [
			"/books/Galat/01.md",
			"/books/Galat/02.md",
			"/books/Galat/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Epesaciner",
		slug: "Epesaciner",
		cover: "/books/Epesaciner/cover.jpg",
		chapters: [
			"/books/Epesaciner/01.md",
			"/books/Epesaciner/02.md",
			"/books/Epesaciner/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Filipic",
		slug: "Filipic",
		cover: "/books/Filipic/cover.jpg",
		chapters: [
			"/books/Filipic/01.md",
			"/books/Filipic/02.md",
			"/books/Filipic/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Kolosaciner",
		slug: "Kolosaciner",
		cover: "/books/Kolosaciner/cover.jpg",
		chapters: [
			"/books/Kolosaciner/01.md",
			"/books/Kolosaciner/02.md",
			"/books/Kolosaciner/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Tesagonikaciner1",
		slug: "Tesagonikaciner1",
		cover: "/books/Tesagonikaciner1/cover.jpg",
		chapters: [
			"/books/Tesagonikaciner1/01.md",
			"/books/Tesagonikaciner1/02.md",
			"/books/Tesagonikaciner1/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Tesagonikaciner2",
		slug: "Tesagonikaciner2",
		cover: "/books/Tesagonikaciner2/cover.jpg",
		chapters: [
			"/books/Tesagonikaciner2/01.md",
			"/books/Tesagonikaciner2/02.md",
			"/books/Tesagonikaciner2/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Timofey1",
		slug: "Timofey1",
		cover: "/books/Timofey1/cover.jpg",
		chapters: [
			"/books/Timofey1/01.md",
			"/books/Timofey1/02.md",
			"/books/Timofey1/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Timofey2",
		slug: "Timofey2",
		cover: "/books/Timofey2/cover.jpg",
		chapters: [
			"/books/Timofey2/01.md",
			"/books/Timofey2/02.md",
			"/books/Timofey2/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Titos",
		slug: "Titos",
		cover: "/books/Titos/cover.jpg",
		chapters: [
			"/books/Titos/01.md",
			"/books/Titos/02.md",
			"/books/Titos/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Filimon",
		slug: "Filimon",
		cover: "/books/Filimon/cover.jpg",
		chapters: [
			"/books/Filimon/01.md",
			"/books/Filimon/02.md",
			"/books/Filimon/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Evreyam",
		slug: "Evreyam",
		cover: "/books/Evreyam/cover.jpg",
		chapters: [
			"/books/Evreyam/01.md",
			"/books/Evreyam/02.md",
			"/books/Evreyam/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Yakov",
		slug: "Yakov",
		cover: "/books/Yakov/cover.jpg",
		chapters: [
			"/books/Yakov/01.md",
			"/books/Yakov/02.md",
			"/books/Yakov/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Petros1",
		slug: "Petros1",
		cover: "/books/Petros1/cover.jpg",
		chapters: [
			"/books/Petros1/01.md",
			"/books/Petros1/02.md",
			"/books/Petros1/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Petros2",
		slug: "Petros2",
		cover: "/books/Petros2/cover.jpg",
		chapters: [
			"/books/Petros2/01.md",
			"/books/Petros2/02.md",
			"/books/Petros2/03.md",
		],
	},
	{
		category: "tutorials",
		title: "John1",
		slug: "John1",
		cover: "/books/John1/cover.jpg",
		chapters: [
			"/books/John1/01.md",
			"/books/John1/02.md",
			"/books/John1/03.md",
		],
	},
	{
		category: "tutorials",
		title: "John2",
		slug: "John2",
		cover: "/books/John2/cover.jpg",
		chapters: [
			"/books/John2/01.md",
			"/books/John2/02.md",
			"/books/John2/03.md",
		],
	},
	{
		category: "tutorials",
		title: "John3",
		slug: "John3",
		cover: "/books/John3/cover.jpg",
		chapters: [
			"/books/John3/01.md",
			"/books/John3/02.md",
			"/books/John3/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Yuda",
		slug: "Yuda",
		cover: "/books/Yuda/cover.jpg",
		chapters: [
			"/books/Yuda/01.md",
			"/books/Yuda/02.md",
			"/books/Yuda/03.md",
		],
	},
	{
		category: "tutorials",
		title: "Haytnutyun",
		slug: "Haytnutyun",
		cover: "/books/Haytnutyun/cover.jpg",
		chapters: [
			"/books/Haytnutyun/01.md",
			"/books/Haytnutyun/02.md",
			"/books/Haytnutyun/03.md",
		],
	},

	// +++++++++++++++++++++++++++ОТЦЫ ВЕРЫ++++++++++++++++++++++++++++++++++++++++++++
	{
		category: "tasks",
		title: "Lusavorich",
		slug: "Lusavorich",
		cover: "/books/Lusavorich/cover.jpg",
		chapters: ["/books/Lusavorich/01.md", "/books/Lusavorich/02.md"],
	},
	{
		category: "tasks",
		title: "Tumanyan",
		slug: "Tumanyan",
		cover: "/books/Tumanyan/cover.jpg",
		chapters: ["/books/Tumanyan/01.md", "/books/Tumanyan/02.md"],
	},
	{
		category: "tasks",
		title: "Narekaci",
		slug: "Narekaci",
		cover: "/books/Narekaci/cover.jpg",
		chapters: [
			"/books/Narekaci/01.md",
			"/books/Narekaci/02.md",
			"/books/Narekaci/02.md",
		],
	},
	{
		category: "tasks",
		title: "Nerses",
		slug: "Nerses",
		cover: "/books/Nerses/cover.jpg",
		chapters: [
			"/books/Nerses/01.md",
			"/books/Nerses/02.md",
			"/books/Nerses/02.md",
		],
	},
	{
		category: "tasks",
		title: "Xorenaci",
		slug: "Xorenaci",
		cover: "/books/Xorenaci/cover.jpg",
		chapters: [
			"/books/Xorenaci/01.md",
			"/books/Xorenaci/02.md",
			"/books/Xorenaci/02.md",
		],
	},

	// +++++++++++++++++++++++++++++++++++++ВЕТХИЙ ЗАВЕТ+++++++++++++++++++++++++++++++++

	{
		category: "taskBook",
		title: "Genesis",
		slug: "Genesis",
		cover: "/books/Genesis/cover.jpg",
		chapters: ["/books/Genesis/01.md", "/books/Genesis/02.md"],
	},
	{
		category: "taskBook",
		title: "Exodus",
		slug: "Exodus",
		cover: "/books/Exodus/cover.jpg",
		chapters: ["/books/Exodus/01.md", "/books/Exodus/02.md"],
	},
	{
		category: "taskBook",
		title: "Levit",
		slug: "Levit",
		cover: "/books/Levit/cover.jpg",
		chapters: ["/books/Levit/01.md", "/books/Levit/02.md"],
	},
	{
		category: "taskBook",
		title: "Numbers",
		slug: "Numbers",
		cover: "/books/Numbers/cover.jpg",
		chapters: ["/books/Numbers/01.md", "/books/Numbers/02.md"],
	},
	{
		category: "taskBook",
		title: "Deuter",
		slug: "Deuter",
		cover: "/books/Deuter/cover.jpg",
		chapters: ["/books/Deuter/01.md", "/books/Deuter/02.md"],
	},
	{
		category: "taskBook",
		title: "Joshua",
		slug: "Joshua",
		cover: "/books/Joshua/cover.jpg",
		chapters: ["/books/Joshua/01.md", "/books/Joshua/02.md"],
	},
	{
		category: "taskBook",
		title: "Judges",
		slug: "Judges",
		cover: "/books/Judges/cover.jpg",
		chapters: ["/books/Judges/01.md", "/books/Judges/02.md"],
	},
	{
		category: "taskBook",
		title: "Ruth",
		slug: "Ruth",
		cover: "/books/Ruth/cover.jpg",
		chapters: ["/books/Ruth/01.md", "/books/Ruth/02.md"],
	},
	{
		category: "taskBook",
		title: "Kings1",
		slug: "Kings1",
		cover: "/books/Kings1/cover.jpg",
		chapters: ["/books/Kings1/01.md", "/books/Kings1/02.md"],
	},
	{
		category: "taskBook",
		title: "Kings2",
		slug: "Kings2",
		cover: "/books/Kings2/cover.jpg",
		chapters: ["/books/Kings2/01.md", "/books/Kings2/02.md"],
	},
	{
		category: "taskBook",
		title: "Kings3",
		slug: "King3",
		cover: "/books/Kings3/cover.jpg",
		chapters: ["/books/Kings3/01.md", "/books/Kings3/02.md"],
	},
	{
		category: "taskBook",
		title: "Kings4",
		slug: "Kings4",
		cover: "/books/Kings4/cover.jpg",
		chapters: ["/books/Kings4/01.md", "/books/Kings4/02.md"],
	},
	{
		category: "taskBook",
		title: "Chronic1",
		slug: "Chronic1",
		cover: "/books/Chronic1/cover.jpg",
		chapters: ["/books/Chronic1/01.md", "/books/Chronic1/02.md"],
	},
	{
		category: "taskBook",
		title: "Chronic2",
		slug: "Chronic2",
		cover: "/books/Chronic2/cover.jpg",
		chapters: ["/books/Chronic2/01.md", "/books/Chronic2/02.md"],
	},
	{
		category: "taskBook",
		title: "Ezdra",
		slug: "Ezdra",
		cover: "/books/Ezdra/cover.jpg",
		chapters: ["/books/Ezdra/01.md", "/books/Ezdra/02.md"],
	},
	{
		category: "taskBook",
		title: "Nehemiah",
		slug: "Nehemiah",
		cover: "/books/Nehemiah/cover.jpg",
		chapters: ["/books/Nehemiah/01.md", "/books/Nehemiah/02.md"],
	},
	{
		category: "taskBook",
		title: "Esther",
		slug: "Esther",
		cover: "/books/Esther/cover.jpg",
		chapters: ["/books/Esther/01.md", "/books/Esther/02.md"],
	},
	{
		category: "taskBook",
		title: "Job",
		slug: "Job",
		cover: "/books/Job/cover.jpg",
		chapters: ["/books/Job/01.md", "/books/Job/02.md"],
	},
	{
		category: "taskBook",
		title: "Proverbs",
		slug: "Proverbs",
		cover: "/books/Proverbs/cover.jpg",
		chapters: ["/books/Proverbs/01.md", "/books/Proverbs/02.md"],
	},
	{
		category: "taskBook",
		title: "Ecclesiast",
		slug: "Ecclesiast",
		cover: "/books/Ecclesiast/cover.jpg",
		chapters: ["/books/Ecclesiast/01.md", "/books/Ecclesiast/02.md"],
	},
	{
		category: "taskBook",
		title: "SongOfSolomon",
		slug: "SongOfSolomon",
		cover: "/books/SongOfSolomon/cover.jpg",
		chapters: ["/books/SongOfSolomon/01.md", "/books/SongOfSolomon/02.md"],
	},
	{
		category: "taskBook",
		title: "Esaya",
		slug: "Esaya",
		cover: "/books/Esaya/cover.jpg",
		chapters: ["/books/Esaya/01.md", "/books/Esaya/02.md"],
	},
	{
		category: "taskBook",
		title: "Jeremiah",
		slug: "Jeremiah",
		cover: "/books/Jeremiah/cover.jpg",
		chapters: ["/books/Jeremiah/01.md", "/books/Jeremiah/02.md"],
	},
	{
		category: "taskBook",
		title: "PlachJeremiah",
		slug: "PlachJeremiah",
		cover: "/books/PlachJeremiah/cover.jpg",
		chapters: ["/books/PlachJeremiah/01.md", "/books/PlachJeremiah/02.md"],
	},
	{
		category: "taskBook",
		title: "Ezekiel",
		slug: "Ezekiel",
		cover: "/books/Ezekiel/cover.jpg",
		chapters: ["/books/Ezekiel/01.md", "/books/Ezekiel/02.md"],
	},
	{
		category: "taskBook",
		title: "Daniel",
		slug: "Daniel",
		cover: "/books/Daniel/cover.jpg",
		chapters: ["/books/Daniel/01.md", "/books/Daniel/02.md"],
	},
	{
		category: "taskBook",
		title: "Osia",
		slug: "Osia",
		cover: "/books/Osia/cover.jpg",
		chapters: ["/books/Osia/01.md", "/books/Osia/02.md"],
	},
	{
		category: "taskBook",
		title: "Hovel",
		slug: "Hovel",
		cover: "/books/Hovel/cover.jpg",
		chapters: ["/books/Hovel/01.md", "/books/Hovel/02.md"],
	},
	{
		category: "taskBook",
		title: "Amos",
		slug: "Amos",
		cover: "/books/Amos/cover.jpg",
		chapters: ["/books/Amos/01.md", "/books/Amos/02.md"],
	},
	{
		category: "taskBook",
		title: "Abdiah",
		slug: "Abdiah",
		cover: "/books/Abdiah/cover.jpg",
		chapters: ["/books/Abdiah/01.md", "/books/Abdiah/02.md"],
	},

	{
		category: "taskBook",
		title: "Hovnan",
		slug: "Hovnan",
		cover: "/books/Hovnan/cover.jpg",
		chapters: ["/books/Hovnan/01.md", "/books/Hovnan/02.md"],
	},
	{
		category: "taskBook",
		title: "Mikia",
		slug: "Mikia",
		cover: "/books/Mikia/cover.jpg",
		chapters: ["/books/Mikia/01.md", "/books/Mikia/02.md"],
	},
	{
		category: "taskBook",
		title: "Naum",
		slug: "Naum",
		cover: "/books/Naum/cover.jpg",
		chapters: ["/books/Naum/01.md", "/books/Naum/02.md"],
	},
	{
		category: "taskBook",
		title: "Abbacum",
		slug: "Abbacum",
		cover: "/books/Abbacum/cover.jpg",
		chapters: ["/books/Abbacum/01.md", "/books/Abbacum/02.md"],
	},

	{
		category: "taskBook",
		title: "Sofonia",
		slug: "Sofonia",
		cover: "/books/Sofonia/cover.jpg",
		chapters: ["/books/Sofonia/01.md", "/books/Sofonia/02.md"],
	},
	{
		category: "taskBook",
		title: "Ange",
		slug: "Ange",
		cover: "/books/Ange/cover.jpg",
		chapters: ["/books/Ange/01.md", "/books/Ange/02.md"],
	},
	{
		category: "taskBook",
		title: "Zakaria",
		slug: "Zakaria",
		cover: "/books/Zakaria/cover.jpg",
		chapters: ["/books/Zakaria/01.md", "/books/Zakaria/02.md"],
	},
	{
		category: "taskBook",
		title: "Malaxia",
		slug: "Malaxia",
		cover: "/books/Malaxia/cover.jpg",
		chapters: ["/books/Malaxia/01.md", "/books/Malaxia/02.md"],
	},
];

export default books;
